language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install mock pytest pytest-cov coveralls
    - pip install -e .
script: py.test jellyfish/test.py --cov jellyfish
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
