language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pypy
script: tox -e $TOX_ENV
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
