language: python
python: 2.7
os:
    - linux
    - osx
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pypy
install: pip install tox
script: tox -e $TOX_ENV
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
