environment:
    global:
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.run_with_env.cmd"
    
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7.9"
          PYTHON_ARCH: "32"
        - PYTHON: "C:\\Python34"
          PYTHON_VERSION: "3.4.3"
          PYTHON_ARCH: "32"

install:
    - "git submodule update --init --recursive"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "python --version"
    - "%CMD_IN_ENV% pip install -e ."
    - "%CMD_IN_ENV% pip install -e pytest unicodecsv"

build: false

test_script:
    - "%CMD_IN_ENV% py.test jellyfish/test.py"
